# Generated by Django 6.0.4 on 2026-04-26 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to='purchases.purchaseorderitem'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('sku', 'created_by')},
        ),
    ]
